---
name: libperl++
version: 0.002
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: 'Embedding and extending perl with C++ made simple'
license: perl
resources:
  bugtracker: http://github.com/Leont/libperl--/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/libperl--/tree
requires:
  perl: 5.008
build_requires:
  Archive::Tar: 0
  ExtUtils::CBuilder: 0.27
  TAP::Harness: 3
configure_requires:
  ExtUtils::CBuilder: 0.27
provides:
  Perlpp::Extend:
    file: lib/Perlpp/Extend.pm
    version: 0.002
no_index:
  directory:
    - t
    - inc
    - examples
generated_by: Leon Timmermans
dynamic_config: 1
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - embedding
  - extending
  - 'C++'
