=pod

=head1 NAME

libperl++ - 

=head1 VERSION

This documentation refers to libperl++ version 0.0.48

=head1 SYNOPSIS

	#Something

=head1 DESCRIPTION

The Interpreter class is the central point of this library. From it you can derive all other values you need.

=head1 ACCESSING PERL FROM C++

=head1 ACCESSING C++ FROM PERL

Exporting C++ functions and variables is explained in L<Exporting.pod>

=head1 AUTHOR

Leon Timmermans (fawaka@gmail.com)

=cut
