=pod

=head1 NAME

libperl++ - Tutorial

=head1 VERSION

XXX

=head1 INSTALLATION

Currently the recommended way to get libperl++ is to checkout the latest version from git at L<git://github.com/Leont/libperl--.git>. Releases are currently not made but will be made in the future. It can be installed using by issuing:

 perl Build.PL
 ./Build
 ./Build test
 ./Build install

For more information, see L<Install>.

=head1 GETTING STARTED

libperl++ is a library for embedding perl. In this tutorial I'm taking simple imaginary game and expose the C++ and perl sides to each other. First of all, we need an interpreter object. For this simple game, we'll use a global interpreter:

 static Interpreter universe;

Using the interpreter we can access perl variables and functions. This is the starting point for all uses of this library.

=head1 ACCESSING PERL

Accessing Perl is L<Interpreter/"ACCESSING PERL FROM C++">.

=head1 USING PERL VALUES

libperl++ defines a number of value type corresponding to Perl values. Use of these values is described in L<Scalar>, L<Array> and L<Hash>. They are best read in that order.

=head1 EXPORTING C++

Exporting C++ to Perl is described in L<Interpreter/"ACCESSING C++ FROM PERL"> and L<Package>.

=head1 EXTENDING PERL

XXX

=head1 AUTHOR

Leon Timmermans (fawaka@gmail.com)

=cut
